// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: block_and_report.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBlock = `-- name: CreateBlock :one
INSERT INTO blocks (blocker_id, blocked_id, created_at)
VALUES (
    $1,
    $2,
    $3
)
RETURNING blocker_id, blocked_id, created_at
`

type CreateBlockParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error) {
	row := q.db.QueryRowContext(ctx, createBlock, arg.BlockerID, arg.BlockedID, arg.CreatedAt)
	var i Block
	err := row.Scan(&i.BlockerID, &i.BlockedID, &i.CreatedAt)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, reported_id, reason, details)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING report_id, reporter_id, reported_id, reason, details, created_at
`

type CreateReportParams struct {
	ReporterID uuid.UUID
	ReportedID uuid.UUID
	Reason     string
	Details    sql.NullString
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport,
		arg.ReporterID,
		arg.ReportedID,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.ReporterID,
		&i.ReportedID,
		&i.Reason,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlockByBlockerAndBlockedID = `-- name: DeleteBlockByBlockerAndBlockedID :exec
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type DeleteBlockByBlockerAndBlockedIDParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) DeleteBlockByBlockerAndBlockedID(ctx context.Context, arg DeleteBlockByBlockerAndBlockedIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlockByBlockerAndBlockedID, arg.BlockerID, arg.BlockedID)
	return err
}

const getBlocksByBlockerID = `-- name: GetBlocksByBlockerID :many
SELECT blocker_id, blocked_id, created_at FROM blocks WHERE blocker_id = $1
`

func (q *Queries) GetBlocksByBlockerID(ctx context.Context, blockerID uuid.UUID) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getBlocksByBlockerID, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Block
	for rows.Next() {
		var i Block
		if err := rows.Scan(&i.BlockerID, &i.BlockedID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const existsBlockByBlockerAndBlockedID = `-- name: existsBlockByBlockerAndBlockedID :one
SELECT blocker_id, blocked_id, created_at FROM blocks WHERE (blocker_id = $1 AND blocked_id = $2) OR (blocker_id = $2 AND blocked_id = $1)
`

type existsBlockByBlockerAndBlockedIDParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) existsBlockByBlockerAndBlockedID(ctx context.Context, arg existsBlockByBlockerAndBlockedIDParams) (Block, error) {
	row := q.db.QueryRowContext(ctx, existsBlockByBlockerAndBlockedID, arg.BlockerID, arg.BlockedID)
	var i Block
	err := row.Scan(&i.BlockerID, &i.BlockedID, &i.CreatedAt)
	return i, err
}
