// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (user_one_id, user_two_id)
VALUES (
    $1,
    $2
)
RETURNING chat_id, user_one_id, user_two_id, created_at, updated_at
`

type CreateChatParams struct {
	UserOneID uuid.UUID
	UserTwoID uuid.UUID
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, createChat, arg.UserOneID, arg.UserTwoID)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.UserOneID,
		&i.UserTwoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChatByID = `-- name: DeleteChatByID :exec
DELETE FROM chats WHERE chat_id = $1
`

func (q *Queries) DeleteChatByID(ctx context.Context, chatID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChatByID, chatID)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT chat_id, user_one_id, user_two_id, created_at, updated_at FROM chats WHERE chat_id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, chatID uuid.UUID) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByID, chatID)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.UserOneID,
		&i.UserTwoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatByUserIDs = `-- name: GetChatByUserIDs :one
SELECT chat_id, user_one_id, user_two_id, created_at, updated_at FROM chats WHERE (user_one_id = $1 AND user_two_id = $2) OR (user_one_id = $2 AND user_two_id = $1)
`

type GetChatByUserIDsParams struct {
	UserOneID uuid.UUID
	UserTwoID uuid.UUID
}

func (q *Queries) GetChatByUserIDs(ctx context.Context, arg GetChatByUserIDsParams) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChatByUserIDs, arg.UserOneID, arg.UserTwoID)
	var i Chat
	err := row.Scan(
		&i.ChatID,
		&i.UserOneID,
		&i.UserTwoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatsByUserID = `-- name: GetChatsByUserID :many
SELECT chat_id, user_one_id, user_two_id, created_at, updated_at FROM chats WHERE user_one_id = $1 OR user_two_id = $1
`

func (q *Queries) GetChatsByUserID(ctx context.Context, userOneID uuid.UUID) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, getChatsByUserID, userOneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ChatID,
			&i.UserOneID,
			&i.UserTwoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
