// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_id, content)
VALUES (
    $1,
    $2,
    $3
)
RETURNING message_id, chat_id, sender_id, content, created_at, updated_at
`

type CreateMessageParams struct {
	ChatID   uuid.UUID
	SenderID uuid.UUID
	Content  string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessageByID = `-- name: DeleteMessageByID :exec
DELETE FROM messages WHERE message_id = $1
`

func (q *Queries) DeleteMessageByID(ctx context.Context, messageID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteMessageByID, messageID)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT message_id, chat_id, sender_id, content, created_at, updated_at FROM messages WHERE message_id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, messageID uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, messageID)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesByChatID = `-- name: GetMessagesByChatID :many
SELECT message_id, chat_id, sender_id, content, created_at, updated_at FROM messages WHERE chat_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetMessagesByChatID(ctx context.Context, chatID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChatID, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.MessageID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesBySenderID = `-- name: GetMessagesBySenderID :many
SELECT message_id, chat_id, sender_id, content, created_at, updated_at FROM messages WHERE sender_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetMessagesBySenderID(ctx context.Context, senderID uuid.UUID) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesBySenderID, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.MessageID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
