// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID       uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	DateOfBirth  time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
