// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ChatID    uuid.UUID
	UserOneID uuid.UUID
	UserTwoID uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	MessageID uuid.UUID
	ChatID    uuid.UUID
	SenderID  uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	TokenHash string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
}

type User struct {
	UserID       uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	DateOfBirth  time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
