// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_notif.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens WHERE token = $1
`

func (q *Queries) DeletePushToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deletePushToken, token)
	return err
}

const deletePushTokenForUser = `-- name: DeletePushTokenForUser :exec
DELETE FROM push_tokens WHERE token = $1 AND user_id = $2
`

type DeletePushTokenForUserParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) DeletePushTokenForUser(ctx context.Context, arg DeletePushTokenForUserParams) error {
	_, err := q.db.ExecContext(ctx, deletePushTokenForUser, arg.Token, arg.UserID)
	return err
}

const getPushTokensByUserID = `-- name: GetPushTokensByUserID :many
SELECT token FROM push_tokens WHERE user_id = $1
`

func (q *Queries) GetPushTokensByUserID(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPushTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushToken = `-- name: UpsertPushToken :exec
INSERT INTO push_tokens (token, user_id)
VALUES (
    $1, 
    $2
)
ON CONFLICT (token)
DO UPDATE SET user_id = EXCLUDED.user_id, updated_at = NOW()
`

type UpsertPushTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertPushToken, arg.Token, arg.UserID)
	return err
}
