// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stories.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createStory = `-- name: CreateStory :one
INSERT INTO stories (user_id, media_url, media_type, expires_at)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING story_id, user_id, media_url, media_type, created_at, expires_at
`

type CreateStoryParams struct {
	UserID    uuid.UUID
	MediaUrl  string
	MediaType string
	ExpiresAt time.Time
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRowContext(ctx, createStory,
		arg.UserID,
		arg.MediaUrl,
		arg.MediaType,
		arg.ExpiresAt,
	)
	var i Story
	err := row.Scan(
		&i.StoryID,
		&i.UserID,
		&i.MediaUrl,
		&i.MediaType,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteStoryByID = `-- name: DeleteStoryByID :exec
DELETE FROM stories WHERE story_id = $1 AND user_id = $2
`

type DeleteStoryByIDParams struct {
	StoryID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) DeleteStoryByID(ctx context.Context, arg DeleteStoryByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteStoryByID, arg.StoryID, arg.UserID)
	return err
}

const didUserViewStory = `-- name: DidUserViewStory :one

SELECT story_id, viewer_id, viewed_at FROM story_views WHERE story_id = $1 AND viewer_id = $2
`

type DidUserViewStoryParams struct {
	StoryID  uuid.UUID
	ViewerID uuid.UUID
}

// active stories, did i see it or did i not.
func (q *Queries) DidUserViewStory(ctx context.Context, arg DidUserViewStoryParams) (StoryView, error) {
	row := q.db.QueryRowContext(ctx, didUserViewStory, arg.StoryID, arg.ViewerID)
	var i StoryView
	err := row.Scan(&i.StoryID, &i.ViewerID, &i.ViewedAt)
	return i, err
}

const getActiveStories = `-- name: GetActiveStories :many
SELECT story_id, user_id, media_url, media_type, created_at, expires_at FROM stories WHERE expires_at > NOW() ORDER BY created_at DESC
`

func (q *Queries) GetActiveStories(ctx context.Context) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, getActiveStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Story
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.StoryID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveStoriesByUserID = `-- name: GetActiveStoriesByUserID :many
SELECT story_id, user_id, media_url, media_type, created_at, expires_at FROM stories WHERE user_id = $1 AND expires_at > NOW() ORDER BY created_at DESC
`

func (q *Queries) GetActiveStoriesByUserID(ctx context.Context, userID uuid.UUID) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, getActiveStoriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Story
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.StoryID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoryByID = `-- name: GetStoryByID :one
SELECT story_id, user_id, media_url, media_type, created_at, expires_at FROM stories WHERE story_id = $1
`

func (q *Queries) GetStoryByID(ctx context.Context, storyID uuid.UUID) (Story, error) {
	row := q.db.QueryRowContext(ctx, getStoryByID, storyID)
	var i Story
	err := row.Scan(
		&i.StoryID,
		&i.UserID,
		&i.MediaUrl,
		&i.MediaType,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getStoryViewsByUserID = `-- name: GetStoryViewsByUserID :many
SELECT stories.story_id, stories.user_id, stories.media_url, stories.media_type, stories.created_at, stories.expires_at, story_views.viewed_at FROM stories LEFT JOIN story_views ON stories.story_id = story_views.story_id AND story_views.viewer_id = $1 
WHERE stories.expires_at > NOW() ORDER BY stories.created_at DESC
`

type GetStoryViewsByUserIDRow struct {
	StoryID   uuid.UUID
	UserID    uuid.UUID
	MediaUrl  string
	MediaType string
	CreatedAt time.Time
	ExpiresAt time.Time
	ViewedAt  sql.NullTime
}

func (q *Queries) GetStoryViewsByUserID(ctx context.Context, viewerID uuid.UUID) ([]GetStoryViewsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoryViewsByUserID, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoryViewsByUserIDRow
	for rows.Next() {
		var i GetStoryViewsByUserIDRow
		if err := rows.Scan(
			&i.StoryID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.ViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerStoryView = `-- name: RegisterStoryView :exec
INSERT INTO story_views (story_id, viewer_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type RegisterStoryViewParams struct {
	StoryID  uuid.UUID
	ViewerID uuid.UUID
}

func (q *Queries) RegisterStoryView(ctx context.Context, arg RegisterStoryViewParams) error {
	_, err := q.db.ExecContext(ctx, registerStoryView, arg.StoryID, arg.ViewerID)
	return err
}
