// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, date_of_birth)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING user_id, username, email, password_hash, date_of_birth, created_at, updated_at, display_name, bio, city, country, hobbies, languages
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
	DateOfBirth  time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DateOfBirth,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.City,
		&i.Country,
		&i.Hobbies,
		&i.Languages,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, password_hash, date_of_birth, created_at, updated_at, display_name, bio, city, country, hobbies, languages FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.City,
		&i.Country,
		&i.Hobbies,
		&i.Languages,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, password_hash, date_of_birth, created_at, updated_at, display_name, bio, city, country, hobbies, languages FROM users WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.Bio,
		&i.City,
		&i.Country,
		&i.Hobbies,
		&i.Languages,
	)
	return i, err
}
