// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usercards.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUserCard = `-- name: CreateUserCard :one
INSERT INTO cards (chat_id, creator_id, subject_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, ciudad_visible, pais_visible, foto_visible, bio_visible, intereses_visible, idiomas_visible, created_at, updated_at
`

type CreateUserCardParams struct {
	ChatID    uuid.UUID
	CreatorID uuid.UUID
	SubjectID uuid.UUID
}

func (q *Queries) CreateUserCard(ctx context.Context, arg CreateUserCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createUserCard, arg.ChatID, arg.CreatorID, arg.SubjectID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CiudadVisible,
		&i.PaisVisible,
		&i.FotoVisible,
		&i.BioVisible,
		&i.InteresesVisible,
		&i.IdiomasVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE card_id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCard, cardID)
	return err
}

const getCardWithSubjectData = `-- name: GetCardWithSubjectData :one
SELECT 
    c.card_id,
    c.chat_id,
    c.creator_id,
    c.subject_id,
    c.nickname,
    c.notes_on_subject,
    c.display_name_visible,
    c.date_of_birth_visible,
    c.ciudad_visible,
    c.pais_visible,
    c.foto_visible,
    c.bio_visible,
    c.intereses_visible,
    c.idiomas_visible,
    u.display_name,
    u.date_of_birth,
    u.ciudad,
    u.pais,
    u.bio,
    u.intereses,
    u.idiomas
FROM cards c
JOIN users u ON u.user_id = c.subject_id
WHERE c.card_id = $1
`

type GetCardWithSubjectDataRow struct {
	CardID             uuid.UUID
	ChatID             uuid.UUID
	CreatorID          uuid.UUID
	SubjectID          uuid.UUID
	Nickname           sql.NullString
	NotesOnSubject     sql.NullString
	DisplayNameVisible sql.NullBool
	DateOfBirthVisible sql.NullBool
	CiudadVisible      sql.NullBool
	PaisVisible        sql.NullBool
	FotoVisible        sql.NullBool
	BioVisible         sql.NullBool
	InteresesVisible   sql.NullBool
	IdiomasVisible     sql.NullBool
	DisplayName        sql.NullString
	DateOfBirth        time.Time
	Ciudad             sql.NullString
	Pais               sql.NullString
	Bio                sql.NullString
	Intereses          sql.NullString
	Idiomas            sql.NullString
}

func (q *Queries) GetCardWithSubjectData(ctx context.Context, cardID uuid.UUID) (GetCardWithSubjectDataRow, error) {
	row := q.db.QueryRowContext(ctx, getCardWithSubjectData, cardID)
	var i GetCardWithSubjectDataRow
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CiudadVisible,
		&i.PaisVisible,
		&i.FotoVisible,
		&i.BioVisible,
		&i.InteresesVisible,
		&i.IdiomasVisible,
		&i.DisplayName,
		&i.DateOfBirth,
		&i.Ciudad,
		&i.Pais,
		&i.Bio,
		&i.Intereses,
		&i.Idiomas,
	)
	return i, err
}

const getUserCardByChatAndUsers = `-- name: GetUserCardByChatAndUsers :one
SELECT card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, ciudad_visible, pais_visible, foto_visible, bio_visible, intereses_visible, idiomas_visible, created_at, updated_at FROM cards WHERE card_id = $1 AND creator_id = $2 AND subject_id = $3
`

type GetUserCardByChatAndUsersParams struct {
	CardID    uuid.UUID
	CreatorID uuid.UUID
	SubjectID uuid.UUID
}

func (q *Queries) GetUserCardByChatAndUsers(ctx context.Context, arg GetUserCardByChatAndUsersParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getUserCardByChatAndUsers, arg.CardID, arg.CreatorID, arg.SubjectID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CiudadVisible,
		&i.PaisVisible,
		&i.FotoVisible,
		&i.BioVisible,
		&i.InteresesVisible,
		&i.IdiomasVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCardsByCreator = `-- name: GetUserCardsByCreator :many
SELECT card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, ciudad_visible, pais_visible, foto_visible, bio_visible, intereses_visible, idiomas_visible, created_at, updated_at FROM cards WHERE creator_id = $1
`

func (q *Queries) GetUserCardsByCreator(ctx context.Context, creatorID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getUserCardsByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.CardID,
			&i.ChatID,
			&i.CreatorID,
			&i.SubjectID,
			&i.Nickname,
			&i.NotesOnSubject,
			&i.DisplayNameVisible,
			&i.DateOfBirthVisible,
			&i.CiudadVisible,
			&i.PaisVisible,
			&i.FotoVisible,
			&i.BioVisible,
			&i.InteresesVisible,
			&i.IdiomasVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPhotos = `-- name: GetUserPhotos :many
SELECT photo_id, user_id, photo_url, position, created_at FROM user_photos WHERE user_id = $1 ORDER BY position
`

func (q *Queries) GetUserPhotos(ctx context.Context, userID uuid.UUID) ([]UserPhoto, error) {
	rows, err := q.db.QueryContext(ctx, getUserPhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPhoto
	for rows.Next() {
		var i UserPhoto
		if err := rows.Scan(
			&i.PhotoID,
			&i.UserID,
			&i.PhotoUrl,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCard = `-- name: ResetCard :exec
UPDATE cards SET nickname = NULL,
    notes_on_subject = NULL,
    display_name_visible = false,
    date_of_birth_visible = false,
    ciudad_visible = false,
    pais_visible = false,
    foto_visible = false,
    bio_visible = false,
    intereses_visible = false,
    idiomas_visible = false,
    updated_at = Now()
WHERE card_id = $1
`

func (q *Queries) ResetCard(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetCard, cardID)
	return err
}

const revealFields = `-- name: RevealFields :exec
UPDATE cards SET display_name_visible = true, date_of_birth_visible = true, ciudad_visible = true,
    pais_visible = true,
    foto_visible = true,
    bio_visible = true,
    intereses_visible = true,
    idiomas_visible = true
WHERE card_id = $1
`

func (q *Queries) RevealFields(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealFields, cardID)
	return err
}

const updateNickname = `-- name: UpdateNickname :exec
UPDATE cards SET nickname = $1, updated_at = Now()  WHERE card_id = $2
`

type UpdateNicknameParams struct {
	Nickname sql.NullString
	CardID   uuid.UUID
}

func (q *Queries) UpdateNickname(ctx context.Context, arg UpdateNicknameParams) error {
	_, err := q.db.ExecContext(ctx, updateNickname, arg.Nickname, arg.CardID)
	return err
}
