// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usercards.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUserCard = `-- name: CreateUserCard :one
INSERT INTO cards (chat_id, creator_id, subject_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, city_visible, country_visible, photos_visible, bio_visible, hobbies_visible, languages_visible, created_at, updated_at
`

type CreateUserCardParams struct {
	ChatID    uuid.UUID
	CreatorID uuid.UUID
	SubjectID uuid.UUID
}

func (q *Queries) CreateUserCard(ctx context.Context, arg CreateUserCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createUserCard, arg.ChatID, arg.CreatorID, arg.SubjectID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CityVisible,
		&i.CountryVisible,
		&i.PhotosVisible,
		&i.BioVisible,
		&i.HobbiesVisible,
		&i.LanguagesVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE card_id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCard, cardID)
	return err
}

const getCardWithChatCreatorAndSubject = `-- name: GetCardWithChatCreatorAndSubject :one
SELECT card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, city_visible, country_visible, photos_visible, bio_visible, hobbies_visible, languages_visible, created_at, updated_at FROM cards WHERE chat_id = $1 AND creator_id = $2 AND subject_id = $3
`

type GetCardWithChatCreatorAndSubjectParams struct {
	ChatID    uuid.UUID
	CreatorID uuid.UUID
	SubjectID uuid.UUID
}

func (q *Queries) GetCardWithChatCreatorAndSubject(ctx context.Context, arg GetCardWithChatCreatorAndSubjectParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardWithChatCreatorAndSubject, arg.ChatID, arg.CreatorID, arg.SubjectID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CityVisible,
		&i.CountryVisible,
		&i.PhotosVisible,
		&i.BioVisible,
		&i.HobbiesVisible,
		&i.LanguagesVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardWithSubjectData = `-- name: GetCardWithSubjectData :one
SELECT 
    c.card_id,
    c.chat_id,
    c.creator_id,
    c.subject_id,
    c.nickname,
    c.notes_on_subject,
    c.display_name_visible,
    c.date_of_birth_visible,
    c.city_visible,
    c.country_visible,
    c.photos_visible,
    c.bio_visible,
    c.hobbies_visible,
    c.languages_visible,
    u.display_name,
    u.date_of_birth,
    u.city,
    u.country,
    u.bio,
    u.hobbies,
    u.languages
FROM cards c
JOIN users u ON u.user_id = c.subject_id
WHERE c.card_id = $1
`

type GetCardWithSubjectDataRow struct {
	CardID             uuid.UUID
	ChatID             uuid.UUID
	CreatorID          uuid.UUID
	SubjectID          uuid.UUID
	Nickname           sql.NullString
	NotesOnSubject     sql.NullString
	DisplayNameVisible sql.NullBool
	DateOfBirthVisible sql.NullBool
	CityVisible        sql.NullBool
	CountryVisible     sql.NullBool
	PhotosVisible      sql.NullBool
	BioVisible         sql.NullBool
	HobbiesVisible     sql.NullBool
	LanguagesVisible   sql.NullBool
	DisplayName        sql.NullString
	DateOfBirth        time.Time
	City               sql.NullString
	Country            sql.NullString
	Bio                sql.NullString
	Hobbies            sql.NullString
	Languages          sql.NullString
}

func (q *Queries) GetCardWithSubjectData(ctx context.Context, cardID uuid.UUID) (GetCardWithSubjectDataRow, error) {
	row := q.db.QueryRowContext(ctx, getCardWithSubjectData, cardID)
	var i GetCardWithSubjectDataRow
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CityVisible,
		&i.CountryVisible,
		&i.PhotosVisible,
		&i.BioVisible,
		&i.HobbiesVisible,
		&i.LanguagesVisible,
		&i.DisplayName,
		&i.DateOfBirth,
		&i.City,
		&i.Country,
		&i.Bio,
		&i.Hobbies,
		&i.Languages,
	)
	return i, err
}

const getUserCardByChatAndUsers = `-- name: GetUserCardByChatAndUsers :one
SELECT card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, city_visible, country_visible, photos_visible, bio_visible, hobbies_visible, languages_visible, created_at, updated_at FROM cards WHERE card_id = $1 AND creator_id = $2 AND subject_id = $3
`

type GetUserCardByChatAndUsersParams struct {
	CardID    uuid.UUID
	CreatorID uuid.UUID
	SubjectID uuid.UUID
}

func (q *Queries) GetUserCardByChatAndUsers(ctx context.Context, arg GetUserCardByChatAndUsersParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getUserCardByChatAndUsers, arg.CardID, arg.CreatorID, arg.SubjectID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CityVisible,
		&i.CountryVisible,
		&i.PhotosVisible,
		&i.BioVisible,
		&i.HobbiesVisible,
		&i.LanguagesVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCardsByCreator = `-- name: GetUserCardsByCreator :many
SELECT card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, city_visible, country_visible, photos_visible, bio_visible, hobbies_visible, languages_visible, created_at, updated_at FROM cards WHERE creator_id = $1
`

func (q *Queries) GetUserCardsByCreator(ctx context.Context, creatorID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getUserCardsByCreator, creatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.CardID,
			&i.ChatID,
			&i.CreatorID,
			&i.SubjectID,
			&i.Nickname,
			&i.NotesOnSubject,
			&i.DisplayNameVisible,
			&i.DateOfBirthVisible,
			&i.CityVisible,
			&i.CountryVisible,
			&i.PhotosVisible,
			&i.BioVisible,
			&i.HobbiesVisible,
			&i.LanguagesVisible,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPhotos = `-- name: GetUserPhotos :many
SELECT photo_id, user_id, photo_url, position, created_at FROM user_photos WHERE user_id = $1 ORDER BY position
`

func (q *Queries) GetUserPhotos(ctx context.Context, userID uuid.UUID) ([]UserPhoto, error) {
	rows, err := q.db.QueryContext(ctx, getUserPhotos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPhoto
	for rows.Next() {
		var i UserPhoto
		if err := rows.Scan(
			&i.PhotoID,
			&i.UserID,
			&i.PhotoUrl,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCard = `-- name: ResetCard :exec
UPDATE cards SET nickname = NULL,
    notes_on_subject = NULL,
    display_name_visible = false,
    date_of_birth_visible = false,
    city_visible = false,
    country_visible = false,
    photos_visible = false,
    bio_visible = false,
    hobbies_visible = false,
    languages_visible = false,
    updated_at = Now()
WHERE card_id = $1
`

func (q *Queries) ResetCard(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetCard, cardID)
	return err
}

const revealBioField = `-- name: RevealBioField :exec
UPDATE cards SET bio_visible = true WHERE card_id = $1
`

func (q *Queries) RevealBioField(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealBioField, cardID)
	return err
}

const revealBirthField = `-- name: RevealBirthField :exec
UPDATE cards SET date_of_birth_visible = true WHERE card_id = $1
`

func (q *Queries) RevealBirthField(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealBirthField, cardID)
	return err
}

const revealCityField = `-- name: RevealCityField :exec
UPDATE cards SET city_visible = true WHERE card_id = $1
`

func (q *Queries) RevealCityField(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealCityField, cardID)
	return err
}

const revealCountryField = `-- name: RevealCountryField :exec
UPDATE cards SET country_visible = true WHERE card_id = $1
`

func (q *Queries) RevealCountryField(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealCountryField, cardID)
	return err
}

const revealFields = `-- name: RevealFields :exec
UPDATE cards SET display_name_visible = true, date_of_birth_visible = true, city_visible = true,
    country_visible = true,
    photos_visible = true,
    bio_visible = true,
    hobbies_visible = true,
    languages_visible = true
WHERE card_id = $1
`

func (q *Queries) RevealFields(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealFields, cardID)
	return err
}

const revealHobbiesField = `-- name: RevealHobbiesField :exec
UPDATE cards SET hobbies_visible = true WHERE card_id = $1
`

func (q *Queries) RevealHobbiesField(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealHobbiesField, cardID)
	return err
}

const revealLanguagesField = `-- name: RevealLanguagesField :exec
UPDATE cards SET languages_visible = true WHERE card_id = $1
`

func (q *Queries) RevealLanguagesField(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealLanguagesField, cardID)
	return err
}

const revealNameField = `-- name: RevealNameField :exec
UPDATE cards SET display_name_visible = true WHERE card_id = $1
`

func (q *Queries) RevealNameField(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealNameField, cardID)
	return err
}

const revealPhotosField = `-- name: RevealPhotosField :exec
UPDATE cards SET photos_visible = true WHERE card_id = $1
`

func (q *Queries) RevealPhotosField(ctx context.Context, cardID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revealPhotosField, cardID)
	return err
}

const updateNickname = `-- name: UpdateNickname :one
UPDATE cards SET nickname = $1, updated_at = Now() WHERE card_id = $2
RETURNING card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, city_visible, country_visible, photos_visible, bio_visible, hobbies_visible, languages_visible, created_at, updated_at
`

type UpdateNicknameParams struct {
	Nickname sql.NullString
	CardID   uuid.UUID
}

func (q *Queries) UpdateNickname(ctx context.Context, arg UpdateNicknameParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateNickname, arg.Nickname, arg.CardID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CityVisible,
		&i.CountryVisible,
		&i.PhotosVisible,
		&i.BioVisible,
		&i.HobbiesVisible,
		&i.LanguagesVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotesOnSubject = `-- name: UpdateNotesOnSubject :one
UPDATE cards SET notes_on_subject = $1, updated_at = Now() WHERE card_id = $2
RETURNING card_id, chat_id, creator_id, subject_id, nickname, notes_on_subject, display_name_visible, date_of_birth_visible, city_visible, country_visible, photos_visible, bio_visible, hobbies_visible, languages_visible, created_at, updated_at
`

type UpdateNotesOnSubjectParams struct {
	NotesOnSubject sql.NullString
	CardID         uuid.UUID
}

func (q *Queries) UpdateNotesOnSubject(ctx context.Context, arg UpdateNotesOnSubjectParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateNotesOnSubject, arg.NotesOnSubject, arg.CardID)
	var i Card
	err := row.Scan(
		&i.CardID,
		&i.ChatID,
		&i.CreatorID,
		&i.SubjectID,
		&i.Nickname,
		&i.NotesOnSubject,
		&i.DisplayNameVisible,
		&i.DateOfBirthVisible,
		&i.CityVisible,
		&i.CountryVisible,
		&i.PhotosVisible,
		&i.BioVisible,
		&i.HobbiesVisible,
		&i.LanguagesVisible,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
